---
- name: add apt key of docker
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: add docker apt repository
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present

- name: install docker
  apt: name=lxc-docker state=present
